### ISSUE TITLE
site launch checklist

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#20]
## Framing / Call to Action
- [x] Make sure that the site has a clear call to action. This should not be 'hey look at this cool tool'. Rather, it should be a way for someone to engage in a meaningful way on the issue being presented.

Some examples:
- Join a mailing list (which means you need to create one)
- Attend an event
- Share on Facebook/Twitter
- Donate to a particular organization
- Create a Tumblr for people to share interesting findings (if it's a data access site)
## Web Search Indexing
- [x] If you have a staging site, tell the search engine robots not to index you with a robots.txt
- [x] Make sure you allow indexing when you are ready to launch.
## Google Analytics
- [x] Create [Google Analytics](http://www.google.com/analytics/) account
- [x] Hook up the GA Tracking Code (typically in our `analytics_lib.js` file)
- [ ] Set up relevant Goals and Funnels
- [ ] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en)
- [ ] Verify site in Webmaster Tools with DNS TXT record
- [ ] Link Webmaster Tools to Google Analytics
## Sharing & Rich Snippets
- [x] Set up general meta tags
  - `<meta name=“description”>`
  - `<meta name=“author”>`
- [x] Set up Facebook meta tags & validate [here](https://developers.facebook.com/tools/debug/)
  - `<meta property=“og:site_name”>`
  - `<meta property=“og:title”>`
  - `<meta property=“og:type”>`
  - `<meta property=“og:description”>`
  - `<meta property=“og:url”>`
  - `<meta property=“og:image”>`
- [x] Set up Twitter meta tags & validate [here](https://cards-dev.twitter.com/validator)
  - `<meta name=“twitter:card”>`
  - `<meta name=“twitter:site”>`
  - `<meta name=“twitter:creator”>`
  - `<meta name=“twitter:description”>` (note that this needs to be under 200 characters)
  - `<meta name=“twitter:title”>`
  - `<meta name=“twitter:url”>`
  - `<meta name=“twitter:image:src”>`
- [ ] Create 2-5 meme images using [Canva](http://canva.com/) or a similar tool
## Mobile Friendliness

Test on various mobile devices:
- [x] scrolling is easy
- [x] nav bar works
- [x] hoverable things are tappable
- [x] charts/maps look ok
## Page Speed
- [x] run the site through https://developers.google.com/speed/pagespeed/insights/
## Miscellaneous Polish
- [x] add favicon
- [x] add 404 & 500 error pages
## Load Testing

If your site relies on a database or server-side code, it should use caching and be load tested. If it's a static HTML or Jekyll site, you can skip this section.
- [x] set up page [caching](https://en.wikipedia.org/wiki/Web_cache)
- [x] write a script to load test all your pages. [Here's a good example from Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/cache_builder.py)
## GitHub Readme

If the site is open source, make sure the Readme.md is complete and accurate. 

Here's a few good examples:
- [Geomancer](https://github.com/associatedpress/geomancer/blob/master/README.md)
- [Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/README.md)

The Readme should have the following sections:
- [x] Overview
- [x] Setup
- [x] Running locally
- [x] Team
- [x] Errors / Bugs 
- [x] Pull Requests
- [x] Copyright and License
## Outreach
- [ ] Write up press release
- [ ] Identify who will be the primary person of contact and make their info prominent on the website and all PR
- [ ] Identify relevant media contacts to email
- [ ] Identify relevant social news sites (reddit, listservs, slack channels)
- [ ] Divide & conquer - send out the media blitz!

**Comment by kwritenow** [comment]
Google Analytics: UA-72762676-1

**Comment by kwritenow** [comment]
This is great, @cathydeng. Did you write this up for this project, or is it a standard template for Chi Hack Night projects?

**Comment by derekeder** [comment]
@kwritenow its something we developed at DataMade: https://github.com/datamade/site-launch-checklist

**Comment by cathydeng** [comment]
added meta tags for twitter & fb, but still need to add images
- [x] take screenshot & add to image meta tags for twitter & fb

**Comment by dianajeanh** [comment]
Favicon options:
![alarm](https://cloud.githubusercontent.com/assets/16910596/12602424/d62a71f0-c46e-11e5-91f4-0dc59e6cc093.png)
![clock](https://cloud.githubusercontent.com/assets/16910596/12602433/e7917254-c46e-11e5-917a-5b9d951a9254.png)
